trigger:
- master

pool:
  name: Default

steps:
- script: |
    whoami
    pwd
    python3 --version

    APP_DIR="$HOME/fastapi-app"

    mkdir -p $APP_DIR

    rsync -av --delete $(Build.SourcesDirectory)/ $APP_DIR/

    cd $APP_DIR

    ls -la

    python3 -m venv venv

    ./venv/bin/pip install --upgrade pip
    ./venv/bin/pip install -r requirements.txt

    ./venv/bin/python run.py
  displayName: 'Debug Deployment'